### ISSUE TITLE
能否支持Vue版本?vue-cli4 vue.config报错

### ISSUE THREAD

**Issue by GordonHuangYong** [fuluteam/antd-icon-reduce-plugin#1]
vue.config配置如下:

> chainWebpack: (config) => {
> ...
> config.plugin('antdIconReducePlugin').use(
>                 new AntdIconReducePlugin({
>                     icons: ['download', { type: 'up', theme: 'outline' }, ...], // 自定义需要加入的图标,支持字符串和对象两种写法，默认为[]
>                     development: false, // 是否在开发环境模式下运行，默认为true
>                     iconFilePath: 'icon', // 指定图标收集文件保存的绝对路径，如果编译后的项目中图标有缺失，可以选择保存到本地，然后再次编译输出即可(该配置项只在mode=production下起作用)
>                 }),
>             )
> }

> configureWebpack: config => {
> ...
> config.module.rules.push({
>                 test: /\.js(x)?$/,
>                 exclude: /node_modules/,
>                 use: ["antd-icon-reduce-loader", "babel-loader"] // 请根据实际情况配置，这里只需要将项目源代码匹配给antd-icon-reduce-loader即可
>             })
> }

报错

> This dependency was not found:
> 
> * @ant-design/icons/lib/dist in ./node_modules/ant-design-vue/es/icon/index.js
> 
> To install it, you can run: npm install --save @ant-design/icons/lib/dist

**Comment by GordonHuangYong** [comment]
> ⠸  Building for production...
> 
>  ERROR  Failed to compile with 1 errors                                                                                                                                                                                  11:16:29 AM
> 
>  error  in ./node_modules/antd-icon-reduce-plugin/antd-icon-reduce.js
> 
> Module build failed (from ./node_modules/antd-icon-reduce-loader/antd-icon-reduce-loader.js):
> Error: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,
> ```
> babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });
> ```
> See https://babeljs.io/docs/en/options#filename for more information.
>

**Comment by lanpangzi-zkg** [comment]
vue版本是没有做支持的
